"""widen_variance_percent_precision

Revision ID: 46a61c9ae54a
Revises: b2c3d4e5f6g7
Create Date: 2026-03-17 07:27:04.157545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a61c9ae54a'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variance_records', 'variance_percent',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variance_records', 'variance_percent',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
