"""initial_schema_v2

Revision ID: bf93fb832bbb
Revises: 
Create Date: 2026-02-26 07:11:59.096895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf93fb832bbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_explanations',
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanations_context_type'), 'ai_explanations', ['context_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='auditaction'), nullable=False),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_info', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('contractors',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_short', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_code'), 'contractors', ['code'], unique=True)
    op.create_table('cost_centers',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_short', sa.String(length=50), nullable=True),
    sa.Column('center_type', sa.Enum('manufacturing', 'product', 'indirect', name='costcentertype'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_code'), 'cost_centers', ['code'], unique=True)
    op.create_index(op.f('ix_cost_centers_parent_id'), 'cost_centers', ['parent_id'], unique=False)
    op.create_table('crude_products',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True, comment='仕込み年度（和暦の年数、例: 38=第38期）'),
    sa.Column('crude_type', sa.Enum('R', 'HI', 'G', 'SP', 'GN', 'other', name='crudeproducttype'), nullable=False),
    sa.Column('aging_years', sa.Integer(), nullable=True, comment='熟成年数'),
    sa.Column('is_blend', sa.Boolean(), nullable=False, comment='ブレンド品（前工程あり）かどうか'),
    sa.Column('blend_source_ids', sa.Text(), nullable=True, comment='ブレンド元の原体コード（JSON配列）'),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_crude_product_code')
    )
    op.create_index(op.f('ix_crude_products_code'), 'crude_products', ['code'], unique=True)
    op.create_table('fiscal_periods',
    sa.Column('year', sa.Integer(), nullable=False, comment='期数（例: 38=第38期）'),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closing', 'closed', name='periodstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_fiscal_period_year_month')
    )
    op.create_table('materials',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('material_type', sa.Enum('raw', 'packaging', 'sub_material', name='materialtype'), nullable=False),
    sa.Column('category', sa.Enum('fruit', 'vegetable', 'grain', 'seaweed', 'other', name='materialcategory'), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('standard_unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=True)
    op.create_table('products',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_short', sa.String(length=50), nullable=True),
    sa.Column('product_group', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.Enum('semi_finished', 'in_house_product_dept', 'in_house_manufacturing', 'outsourced_in_house', 'outsourced', 'special', 'produce', name='producttype'), nullable=False),
    sa.Column('sc_code', sa.String(length=30), nullable=True, comment='SCシステムの品目コード'),
    sa.Column('content_weight_g', sa.Numeric(precision=10, scale=2), nullable=True, comment='内容量(g)'),
    sa.Column('product_symbol', sa.String(length=20), nullable=True, comment='製品記号'),
    sa.Column('gram_unit_price', sa.Numeric(precision=18, scale=6), nullable=True, comment='グラム単価'),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('standard_lot_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_product_group'), 'products', ['product_group'], unique=False)
    op.create_index(op.f('ix_products_sc_code'), 'products', ['sc_code'], unique=False)
    op.create_table('actual_costs',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('crude_product_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='原体原価'),
    sa.Column('packaging_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='資材費'),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='労務費'),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='経費'),
    sa.Column('outsourcing_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='外注加工費'),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_system', sa.Enum('geneki_db', 'sc_system', 'kanjyo_bugyo', 'tsuhan21', 'romu_db', 'product_db', 'manual', name='sourcesystem'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'cost_center_id', 'period_id', name='uq_act_cost_product_cc_period')
    )
    op.create_index(op.f('ix_actual_costs_cost_center_id'), 'actual_costs', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_actual_costs_period_id'), 'actual_costs', ['period_id'], unique=False)
    op.create_index(op.f('ix_actual_costs_product_id'), 'actual_costs', ['product_id'], unique=False)
    op.create_table('allocation_rules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_cost_center_id', sa.UUID(), nullable=False),
    sa.Column('basis', sa.Enum('production_hours', 'raw_material_quantity', 'crude_quantity', 'weight_based', 'manual', name='allocationbasis'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_cost_center_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_headers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('bom_type', sa.Enum('raw_material_process', 'product_process', name='bomtype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('yield_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'bom_type', 'effective_date', name='uq_bom_product_type_date')
    )
    op.create_index(op.f('ix_bom_headers_product_id'), 'bom_headers', ['product_id'], unique=False)
    op.create_table('crude_product_actual_costs',
    sa.Column('crude_product_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='原材料費'),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='労務費'),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='経費'),
    sa.Column('prior_process_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='前工程費'),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='実際数量(kg)'),
    sa.Column('source_system', sa.Enum('geneki_db', 'sc_system', 'kanjyo_bugyo', 'tsuhan21', 'romu_db', 'product_db', 'manual', name='sourcesystem'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crude_product_id'], ['crude_products.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crude_product_id', 'period_id', name='uq_crude_act_cost_product_period')
    )
    op.create_index(op.f('ix_crude_product_actual_costs_crude_product_id'), 'crude_product_actual_costs', ['crude_product_id'], unique=False)
    op.create_index(op.f('ix_crude_product_actual_costs_period_id'), 'crude_product_actual_costs', ['period_id'], unique=False)
    op.create_table('crude_product_standard_costs',
    sa.Column('crude_product_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='原材料費'),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='労務費'),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='経費'),
    sa.Column('prior_process_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='前工程費'),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='標準原価合計'),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='kg単価'),
    sa.Column('standard_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='標準数量(kg)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crude_product_id'], ['crude_products.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crude_product_id', 'period_id', name='uq_crude_std_cost_product_period')
    )
    op.create_index(op.f('ix_crude_product_standard_costs_crude_product_id'), 'crude_product_standard_costs', ['crude_product_id'], unique=False)
    op.create_index(op.f('ix_crude_product_standard_costs_period_id'), 'crude_product_standard_costs', ['period_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('crude_product_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('material_receipt', 'material_usage', 'crude_increase', 'crude_output', 'crude_input', 'finished_goods', 'research', 'promotion', 'adjustment', name='movementtype'), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('aging_start_date', sa.Date(), nullable=True, comment='熟成開始日（原体用）'),
    sa.Column('source_system', sa.Enum('geneki_db', 'sc_system', 'kanjyo_bugyo', 'tsuhan21', 'romu_db', 'product_db', 'manual', name='sourcesystem'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['crude_product_id'], ['crude_products.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_cost_center_id'), 'inventory_movements', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_crude_product_id'), 'inventory_movements', ['crude_product_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_material_id'), 'inventory_movements', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_period_id'), 'inventory_movements', ['period_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_product_id'), 'inventory_movements', ['product_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_a', sa.String(length=50), nullable=False),
    sa.Column('source_b', sa.String(length=50), nullable=False),
    sa.Column('value_a', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_b', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('matched', 'unmatched', 'discrepancy', name='reconciliationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_period_id'), 'reconciliation_results', ['period_id'], unique=False)
    op.create_table('standard_costs',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('crude_product_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='原体原価'),
    sa.Column('packaging_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='資材費'),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='労務費'),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='経費'),
    sa.Column('outsourcing_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='外注加工費'),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='標準原価合計'),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False, comment='製品単位あたり標準原価'),
    sa.Column('lot_size', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'period_id', name='uq_std_cost_product_period')
    )
    op.create_index(op.f('ix_standard_costs_period_id'), 'standard_costs', ['period_id'], unique=False)
    op.create_index(op.f('ix_standard_costs_product_id'), 'standard_costs', ['product_id'], unique=False)
    op.create_table('variance_records',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('variance_type', sa.Enum('price', 'quantity', 'efficiency', 'mix', 'volume', name='variancetype'), nullable=False),
    sa.Column('cost_element', sa.String(length=50), nullable=False),
    sa.Column('standard_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_favorable', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variance_records_cost_center_id'), 'variance_records', ['cost_center_id'], unique=False)
    op.create_index(op.f('ix_variance_records_period_id'), 'variance_records', ['period_id'], unique=False)
    op.create_index(op.f('ix_variance_records_product_id'), 'variance_records', ['product_id'], unique=False)
    op.create_table('allocation_rule_targets',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('target_cost_center_id', sa.UUID(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['allocation_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_cost_center_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_rule_targets_rule_id'), 'allocation_rule_targets', ['rule_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('header_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('crude_product_id', sa.UUID(), nullable=True, comment='原体を使う場合'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('loss_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crude_product_id'], ['crude_products.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['bom_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_header_id'), 'bom_lines', ['header_id'], unique=False)
    op.create_table('cost_allocations',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('source_cost_center_id', sa.UUID(), nullable=False),
    sa.Column('target_cost_center_id', sa.UUID(), nullable=False),
    sa.Column('cost_element', sa.Enum('material', 'crude_product', 'packaging', 'labor', 'overhead', 'outsourcing', 'prior_process', name='costelement'), nullable=True, comment='配賦対象の原価要素'),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('basis_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['allocation_rules.id'], ),
    sa.ForeignKeyConstraint(['source_cost_center_id'], ['cost_centers.id'], ),
    sa.ForeignKeyConstraint(['target_cost_center_id'], ['cost_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_allocations_period_id'), 'cost_allocations', ['period_id'], unique=False)
    op.create_index(op.f('ix_cost_allocations_rule_id'), 'cost_allocations', ['rule_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_batch_id'), 'import_errors', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_cost_allocations_rule_id'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_period_id'), table_name='cost_allocations')
    op.drop_table('cost_allocations')
    op.drop_index(op.f('ix_bom_lines_header_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_allocation_rule_targets_rule_id'), table_name='allocation_rule_targets')
    op.drop_table('allocation_rule_targets')
    op.drop_index(op.f('ix_variance_records_product_id'), table_name='variance_records')
    op.drop_index(op.f('ix_variance_records_period_id'), table_name='variance_records')
    op.drop_index(op.f('ix_variance_records_cost_center_id'), table_name='variance_records')
    op.drop_table('variance_records')
    op.drop_index(op.f('ix_standard_costs_product_id'), table_name='standard_costs')
    op.drop_index(op.f('ix_standard_costs_period_id'), table_name='standard_costs')
    op.drop_table('standard_costs')
    op.drop_index(op.f('ix_reconciliation_results_period_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_inventory_movements_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_period_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_material_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_crude_product_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_cost_center_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_crude_product_standard_costs_period_id'), table_name='crude_product_standard_costs')
    op.drop_index(op.f('ix_crude_product_standard_costs_crude_product_id'), table_name='crude_product_standard_costs')
    op.drop_table('crude_product_standard_costs')
    op.drop_index(op.f('ix_crude_product_actual_costs_period_id'), table_name='crude_product_actual_costs')
    op.drop_index(op.f('ix_crude_product_actual_costs_crude_product_id'), table_name='crude_product_actual_costs')
    op.drop_table('crude_product_actual_costs')
    op.drop_index(op.f('ix_bom_headers_product_id'), table_name='bom_headers')
    op.drop_table('bom_headers')
    op.drop_table('allocation_rules')
    op.drop_index(op.f('ix_actual_costs_product_id'), table_name='actual_costs')
    op.drop_index(op.f('ix_actual_costs_period_id'), table_name='actual_costs')
    op.drop_index(op.f('ix_actual_costs_cost_center_id'), table_name='actual_costs')
    op.drop_table('actual_costs')
    op.drop_index(op.f('ix_products_sc_code'), table_name='products')
    op.drop_index(op.f('ix_products_product_group'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.drop_table('materials')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_crude_products_code'), table_name='crude_products')
    op.drop_table('crude_products')
    op.drop_index(op.f('ix_cost_centers_parent_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_code'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_contractors_code'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_explanations_context_type'), table_name='ai_explanations')
    op.drop_table('ai_explanations')
    # ### end Alembic commands ###
